### ISSUE TITLE
Fix the smoke-test tester image

### ISSUE THREAD

**Issue by maelvls** [jetstack/jetstack-secure-gcm#29]
While reviewing the Jetstack Secure for cert-manager solution, Google bumped into an issue:

```sh
LAST SEEN   TYPE      REASON                 OBJECT                          MESSAGE
2s          Warning   BackoffLimitExceeded   job/apptest-4v6dctp1-deployer   Job has reached the specified backoff limit
3m41s       Warning   Failed                 pod/smoke-test-pod              Failed to pull image "gcr.io/jetstack-mael-valais/jetstack-secure-for-cert-manager/smoke-test:1.1.0-gcm.1": rpc error: code = Unknown desc = Error response from daemon: pull access denied for gcr.io/jetstack-mael-valais/jetstack-secure-for-cert-manager/smoke-test, repository does not exist or may require 'docker login': denied: Permission denied for "1.1.0-gcm.1" from request "/v2/jetstack-mael-valais/jetstack-secure-for-cert-manager/smoke-test/manifests/1.1.0-gcm.1".
3m41s       Warning   Failed                 pod/smoke-test-pod              Error: ErrImagePull
3m26s       Warning   Failed                 pod/smoke-test-pod              Error: ImagePullBackOff
```

The "tester image" mentioned in the above logs is the image used by the "tester pod" as described in [verification-integration.md](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/76f5b4467671746a10396aa322eaa9dbde26a519/docs/verification-integration.md#3-include-a-pod-manifest-to-execute-the-tests). The tester image is built and pushed as part of our [cloud-build.yaml](https://github.com/jetstack/jetstack-secure-gcm/blob/main/cloudbuild.yaml).

In the above error, the tester pod seems to be using the wrong image:

```sh
gcr.io/jetstack-mael-valais/jetstack-secure-for-cert-manager/smoke-test:1.1.0-gcm.1
```

Instead, it should show:

```
gcr.io/jetstack-public/jetstack-secure-for-cert-manager/smoke-test:1.1.0-gcm.1
```

It seems like the helm value `smokeTestImage` is hardcoded into the `deployer:1.1.0-gcm.1` image, which is something I did not think about when I used `envsubst` at [cloudbuild.yaml#L176](https://github.com/jetstack/jetstack-secure-gcm/blob/456f3a1c42ea834ac39cf99882cf50af6afa9093/cloudbuild.yaml#L176-L178). The idea is to set the correct tester image in [data-test/schema.yaml](https://github.com/jetstack/jetstack-secure-gcm/blob/4ca4d0eae812f51136275236b4268da51036d4d2/data-test/schema.yaml#L9-L17):

```yaml
# data-test/schema.yaml
properties:
  smokeTestImage:   # used as "{{.Values.smokeTestImage}}" in tester.yaml
    type: string
    default: $IMAGE.  # ← envsubt'd
    x-google-property:
      type: IMAGE
```

What I did not realize at the time is that the the `deployer:1.1.0-gcm.1` image would end up with:

```yaml
# data-test/schema.yaml
properties:
  smokeTestImage:
    type: string
    default: gcr.io/jetstack-mael-valais/jetstack-secure-for-cert-manager/smoke-test:1.1.0-gcm.1
    x-google-property:
      type: IMAGE
```

The whole issue is that the `deployer:1.1.0-gcm.1` has not been built directly from the `jetstack-public` project.

**Solutions:**

1. Use `x-google-marketplace.images.smoke-test` instead of `properties.smokeTestImage`.
2. Use the `jetstack-public` project in order to build the `deployer:1.1.0-gcm.1` image. Until today, I wasn't able to use it because of missing permissions, so I ended up using my own project `jetstack-mael-valais`.

Since (1) does not seem possible as detailed in the below https://github.com/jetstack/jetstack-secure-gcm/issues/29#issuecomment-790448110). We could ask Google if that is intentional or not.

In the meantime, I propose that we go with the solution (2). I will investigate what permissions are missing and report as a comment to this issue.

cc @james-w

**Comment by maelvls** [comment]
In [mpdev-references.md](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/3187a6ed6c609a15a49ac60461b1fd4bd4fa9ebd/docs/mpdev-references.md#smoke-test-an-application), it says: 

> Properties in `/data-test/schema.yaml` will override properties in `/data/schema.yaml`. This can also be used to overwrite existing default values for verification.

@vcanaa after looking at [this commit](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/commit/aca27e694dc2ab6304a373a0906a802cb26896aa) (2019), I wonder:
- is `mpdev verify` only supporting the top-level `properties` field? e.g.:
  ```yaml
properties:
  preflight.replicaCount:
    type: integer
    default: 0
- Or can we also use it for the `x-google-marketplace.images` field? e.g.:
  ```yaml
  # data-test/schema.yaml
   x-google-marketplace:
    images:
      smoke-test:
        properties:
          smokeTestImage: # used as "{{.Values.smokeTestImage}}" in tester.yaml
            type: FULL
  ```

This information is not available in the [mpdev-references.md](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/3187a6ed6c609a15a49ac60461b1fd4bd4fa9ebd/docs/mpdev-references.md#smoke-test-an-application) unfortunately.
