### ISSUE TITLE
Test the UI and CLI user flows

### ISSUE THREAD

**Issue by maelvls** [jetstack/jetstack-secure-gcm#34]
Requirement: https://github.com/jetstack/platform-board/issues/338 (jetstack private link)

Now that the application [was accepted](https://github.com/jetstack/jetstack-secure-gcm/issues/24#issuecomment-792897961) by Google, the app is in "private" mode. People that can access the jetstack-public project can test it out by going on the [application's page](https://console.cloud.google.com/marketplace/details/jetstack-public/jetstack-secure-for-cert-manager?project=jetstack-dev) and using the jetstack-dev project (since Zee already "Purchased" the app on that project).

The next step is to test the two possible user flows:

- [x] the UI flow, where the user deploys the app by using the [click to deploy instructions](https://platform.jetstack.io/docs/google-cloud-marketplace#click-to-deploy-installation); 
- [x] the CLI flow, where the user deploys the app by using the [CLI instructions](https://platform.jetstack.io/docs/google-cloud-marketplace#cli-installation).

This issue is about trying out both flows and reporting any issue.

**Comment by maelvls** [comment]
The UI flow has a "bug": the only component that shows in the Application page is the ubbagent. It should show the cert-manager deployment, etc

![only-ubbagent-showing](https://user-images.githubusercontent.com/2195781/110634322-20d22b00-81aa-11eb-91af-73debefe2193.png)

**Comment by maelvls** [comment]
Note that the official Application API doc says to use `app.kubernetes.io/name`:

> The selector is used to match resources that belong to the Application. All of the applications resources should have labels such that they match this selector. Users should use the `app.kubernetes.io/name` label on all components of the Application and set the selector to match this label.
>
> For instance,
> ```yaml
> selector:
>   matchLabels:
>     app.kubernetes.io/name: my-cool-app
> ```
> should be used as the selector for an Application named "my-cool-app", and each component should contain a label that matches.

Without realizing that using `app.kubernetes.io/name` was mandatory, @wallrj and I chose to go with `app.kubernetes.io/instance` because the `app.kubernetes.io/name` in the cert-manager helm chart, defined in [_helpers.tpl](https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/templates/_helpers.tpl#L3-L7), defaults to the chart name instead of the release name:

```yaml
app.kubernetes.io/name: {{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
```

Not sure why cert-manager uses the chart name instead of the release name for the `app.kubernetes.io/name`, but I think we

**Comment by maelvls** [comment]
**IDEA 4**: @wallrj and I have found the reason why only the ubbagent was the only deployment that was showing up: the `app.kubernetes.io/name` is automatically added to the matchLabels. So we thought: why not use both `name` and `instance`? The application would look like this:

```yaml
kind: Application
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}          # Will always be "jetstack-secure-gcm"
      app.kubernetes.io/instance: {{ .Release.Name }}    # Example: "jetstack-secure-for-cert-mana-2"
```

First, we set the name override for all our charts:

```yaml
# https://github.com/jetstack/jetstack-secure-gcm/blob/main/chart/jetstack-secure-gcm/values.yaml
cert-manager:
  nameOverride: jetstack-secure-gcm
google-cas-issuer:
  nameOverride: jetstack-secure-gcm
preflight:
  nameOverride: jetstack-secure-gcm
```

Then we make sure all the objects are set with the labels:

```yaml
metadata:
    app.kubernetes.io/name: "{{ .Chart.Name }}"        # Will be "jetstack-secure-gcm" due to the name override
    app.kubernetes.io/instance: "{{ .Release.Name }}"  # Example: "jetstack-secure-for-cert-mana-2"
```

And everything works, all the "components" are showing in the Application UI!

**Comment by maelvls** [comment]
Other findings... Trying to do this approach, everything seemed OK except for the `cainjector`:

```yaml
kind: ReplicaSet
metadata:
  labels:
    app.kubernetes.io/instance: apptest-qd8oe04y
    app.kubernetes.io/name: cainjector
```

I guess I'll just ignore that for now. Just for the record, the explanation is in [_helpers.tpl](https://github.com/jetstack/cert-manager/blob/9f343ec581192fd6ecb41214d1d6672e71739250/deploy/charts/cert-manager/templates/_helpers.tpl#L94-L100):

```yaml
{{/*
Expand the name of the chart.
Manually fix the 'app' and 'name' labels to 'cainjector' to maintain
compatibility with the v0.9 deployment selector.
*/}}
{{- define "cainjector.name" -}}
{{- printf "cainjector" -}}
{{- end -}}
```
