### ISSUE TITLE
Update to cert-manager 1.4

### ISSUE THREAD

**Issue by maelvls** [jetstack/jetstack-secure-gcm#57]
Still to be done as of 6 July 2021:

- [x] Deprecate 1.1 and 1.3 in the Marketplace admin UI.
- [x] Have a review on #60
- [ ] Have a review on https://github.com/jetstack/jetstack-secure-gcm/pull/58
- [ ] Re-submit again and again until the review passes
    - Attempt 1 (20 June 2021)
    - Refusal 1: I submitted 1.3 as the "default" version instead of 1.4 (my fault)
    - [Attempt 2](https://groups.google.com/a/jetstack.io/g/cert-manager-maintainers/c/6epesX1OcNU/m/7dO2I3o2AAAJ) (27 June 2021)
    - [Refusal 2](https://groups.google.com/a/jetstack.io/g/cert-manager-maintainers/c/6epesX1OcNU/m/7dO2I3o2AAAJ): issue the transition from GoogleCASIssuer `v1alpha1` -> `v1beta1`
    - Attempt 3 (29 June 2021)
    - [Refusal 3](https://groups.google.com/a/jetstack.io/g/cert-manager-maintainers/c/6epesX1OcNU/m/hPdkXpVOAQAJ) (29 June 2021): the `testrunner` fails with no clear indication of what is failing
    - [Message](https://groups.google.com/a/jetstack.io/g/cert-manager-maintainers/c/6epesX1OcNU/m/hPdkXpVOAQAJ) from James Westby about our struggles with the `testrunner` (29 June 2021)
    - Google Engineer team [investigating a bug](https://groups.google.com/a/jetstack.io/g/cert-manager-maintainers/c/6epesX1OcNU/m/D18NEjfAAQAJ) with the backend (6 July 2021)
    - [Refusal 4](https://groups.google.com/a/jetstack.io/g/cert-manager-maintainers/c/6epesX1OcNU/m/pSxO5LXEAQAJ): (7 July 2021) the `info` field still present
    - [Attempt 5](https://groups.google.com/a/jetstack.io/g/cert-manager-maintainers/c/6epesX1OcNU/m/aeOmFrPrAQAJ) (8 July 2021), image not changed.
    - [Refusal 5](https://groups.google.com/a/jetstack.io/g/cert-manager-maintainers/c/6epesX1OcNU/m/PW-VQqmSCAAJ) (13 July 2021)

---
[cert-manager v1.4.0](https://github.com/jetstack/cert-manager/releases/tag/v1.4.0) was release on 15 July 2021 and we want to update the jetstack-secure-for-cert-manager app on the Google Cloud Marketplace to be updated within a few days of each release of cert-manager.

Using the [Cutting a new release instructions](https://github.com/jetstack/jetstack-secure-gcm/blob/main/docs/TESTING-DEPLOYER.md#cutting-a-new-release), we shall update the Google Cloud Marketplace app from 1.3.1 to 1.4.0.

:warning: New `Role` have to be added to `schema.yaml`. To see what needs to be added to `schema.yaml`:

```sh
# From the cert-manager repo
git diff origin/release-1.3..origin/release-1.4 deploy/charts/cert-manager
```

`Role` to be added to both the `cainjector` and `controller` service accounts:

```yaml
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    resourceNames: ["cert-manager-cainjector-leader-election", "cert-manager-cainjector-leader-election-core"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create"]
```

`ClusterRole` needed:

```yaml
rules:
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests/status"]
    verbs: ["update"]
  - apiGroups: ["certificates.k8s.io"]
    resources: ["signers"]
    resourceNames: ["issuers.cert-manager.io/*", "clusterissuers.cert-manager.io/*"]
    verbs: ["sign"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
```

**Estimation:** 1 hour
